# Generated by Django 3.1.5 on 2021-04-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='reviews',
        ),
    ]
